version: '3.6'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/go/src/github.com/mtlynch/whatgotdone/backend
      - ./client/dist:/whatgotdone-frontend