version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.11.2-stretch
    steps:
      - checkout
      - run:
          name: Download npm packages
          command: npm --prefix ./client install
      - run:
          name: Lint client
          command: npm --prefix ./client run lint
      - run:
          name: Build production frontend
          command: npm --prefix ./client run build
      - run:
          name: Move dist files
          command: mv ./client/dist /whatgotdone-frontend
      - persist_to_workspace:
          root: /whatgotdone-frontend
          paths:
            - ./*
  deploy:
    docker:
      - image: google/cloud-sdk:240.0.0
    environment:
      GCLOUD_PROJECT: whatgotdone
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Retrieve client secret from CircleCI
          command: |
            echo "$CLIENT_SECRET" | \
              base64 --decode > "${HOME}/client-secret.json"
      - run:
          name: Authenticate gcloud
          command: |
            gcloud auth activate-service-account \
              --key-file "${HOME}/client-secret.json"
      - run:
          name: Configure gcloud project
          command: gcloud config set project "${GCLOUD_PROJECT}"
      - run:
          name: Deploy to AppEngine
          command: gcloud --quiet app deploy app.yaml --promote
workflows:
  version: 2
  test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
