version: '3.2'
services:
  whatgotdone:
    build:
      context: ../
      args:
        NPM_BUILD_MODE: staging
        GO_BUILD_TAGS: staging
        # Use a unique "reactions" key in the datastore (ensures that the
        # datastore is always empty of reactions).
        USE_FRESH_REACTIONS_KEY: 1
    environment:
      - PORT=3123
    volumes:
      - ../service-account-creds-staging.json:/app/service-account-creds-staging.json
      - ./:/app/e2e
  cypress:
    image: "cypress/included:3.3.1"
    depends_on:
      - whatgotdone
    environment:
      - CYPRESS_baseUrl=http://whatgotdone:3123
      - DEBUG=cypress:server:request,cypress:server:server,cypress:server:proxy,cypress:network:agent,cypress:server:browsers
    working_dir: /e2e
    volumes:
      - ./:/e2e
